# resources:
# # Automation scripts source repo
#   - name: git_code_repo
#     type: gitRepo
#     integration: "git_ship"
#     versionTemplate:
#       sourceName: "sanster23/aws-shippable-devops"
#       branch: master


jobs:
  # Run the script for s1
  - name: job_s1
    type: runSh
    steps:
      - IN: git_code_repo
        switch: off
      - IN: trigger_s1
      - TASK:
          name: job_s1
          script:
            - *final_script_temp
            - STATE="$(shipctl get_resource_state "s1_state")"
            - echo $STATE
            - pushd $(shipctl get_resource_state "git_code_repo")
            - echo "${REPOSITORY_URL}"
            - echo "${BASE_BRANCH}"
            - echo "${COMMIT}"
            - echo $SHIPPABLE_COMMIT_RANGE
            # - changes=`git diff --name-only $SHIPPABLE_COMMIT_RANGE | sort -u | awk 'BEGIN {FS="/"} {print $1}' | uniq`
            - changes="$(git diff --name-only $SHIPPABLE_COMMIT_RANGE | sort -u)"
            - echo $changes
            - echo "******\t******\n\n******\t******"
            - git log
            - popd
      - OUT: s1_state
    flags:
      - ship
      - aws